import { storedActions } from './outbox-helpers.mjs';
import { IDBFactory } from 'fake-indexeddb';
globalThis.indexedDB = new IDBFactory();
import assert from 'node:assert/strict';
import { build } from 'esbuild';
import { fileURLToPath } from 'node:url';
const {outputFiles}=await build({stdin:{contents:"export * from './src/api/client'; export * from './src/utils/outbox';",resolveDir:fileURLToPath(new URL('../',import.meta.url)),loader:'ts'},bundle:true,write:false,format:'esm',platform:'node',define:{'import.meta.env':'{}'}});
const store=new Map();let overlap=null;
globalThis.localStorage={getItem(k){const snapshot=store.get(k)??null;if(k==='yuldash.outbox'&&overlap){const fn=overlap;overlap=null;fn();}return snapshot;},setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const locks=new Map();Object.defineProperty(globalThis,'navigator',{configurable:true,value:{locks:{request(name,fn){const next=(locks.get(name)??Promise.resolve()).then(fn);locks.set(name,next.catch(()=>{}));return next;}}}});
const load=tag=>import('data:text/javascript;base64,'+Buffer.from(outputFiles[0].text+'\n//'+tag).toString('base64'));
const clock=Date.now;Date.now=()=>123456789;
const a=await load('append-A'),b=await load('append-B');Date.now=clock;
a.setSession('A','refresh-A');let pendingB;
pendingB=await b.enqueue(42,'message','B');
await a.enqueue(42,'message','A');await pendingB;
const actions=(await storedActions());
assert.deepEqual(actions.map(x=>x.payload).sort(),['A','B'],'Concurrent enqueue overwrote an action');
assert.equal(new Set(actions.map(x=>x.id)).size,2,'Independent tabs assigned the same action id');
const sent=[];globalThis.fetch=async(u,i)=>{sent.push(JSON.parse(i.body).text);return new Response('{}');};
await a.flushOutbox();assert.deepEqual(sent.sort(),['A','B']);
console.log('✓ equal-clock tabs create distinct ids and both messages are delivered');
