"""initial schema

Revision ID: 75accea6f8bd
Revises: 
Create Date: 2026-06-27 15:44:00.870030

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75accea6f8bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ad_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adevent_ad_id'), 'adevent', ['ad_id'], unique=False)
    op.create_index(op.f('ix_adevent_event_type'), 'adevent', ['event_type'], unique=False)
    op.create_table('block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('blocked_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_block_user_id'), 'block', ['user_id'], unique=False)
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'onboard', 'done', 'cancelled', name='bookingstatus'), nullable=False),
    sa.Column('boarding_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_passenger_id'), 'booking', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_booking_ride_id'), 'booking', ['ride_id'], unique=False)
    op.create_table('devicetoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devicetoken_token'), 'devicetoken', ['token'], unique=True)
    op.create_index(op.f('ix_devicetoken_user_id'), 'devicetoken', ['user_id'], unique=False)
    op.create_table('driverprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('trips_count', sa.Integer(), nullable=False),
    sa.Column('car_make', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('car_model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('car_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('car_plate', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('docs_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('car_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verify_submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driverprofile_user_id'), 'driverprofile', ['user_id'], unique=True)
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('voice_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_booking_id'), 'message', ['booking_id'], unique=False)
    op.create_table('otpcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otpcode_phone'), 'otpcode', ['phone'], unique=False)
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('rater_id', sa.Integer(), nullable=False),
    sa.Column('ratee_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_booking_id'), 'rating', ['booking_id'], unique=False)
    op.create_index(op.f('ix_rating_ratee_id'), 'rating', ['ratee_id'], unique=False)
    op.create_index(op.f('ix_rating_rater_id'), 'rating', ['rater_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_reporter_id'), 'report', ['reporter_id'], unique=False)
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('from_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('depart_at', sa.DateTime(), nullable=False),
    sa.Column('seats_total', sa.Integer(), nullable=False),
    sa.Column('seats_left', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('regular', 'hospital', 'parcel', 'cargo', 'urgent', name='ridecategory'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=True),
    sa.Column('pickup_lng', sa.Float(), nullable=True),
    sa.Column('recurrence', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pets_allowed', sa.Boolean(), nullable=False),
    sa.Column('child_seat', sa.Boolean(), nullable=False),
    sa.Column('women_only', sa.Boolean(), nullable=False),
    sa.Column('smoking', sa.Boolean(), nullable=False),
    sa.Column('baggage', sa.Boolean(), nullable=False),
    sa.Column('air_conditioner', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'done', 'cancelled', name='ridestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ride_driver_id'), 'ride', ['driver_id'], unique=False)
    op.create_index(op.f('ix_ride_from_city'), 'ride', ['from_city'], unique=False)
    op.create_index(op.f('ix_ride_to_city'), 'ride', ['to_city'], unique=False)
    op.create_table('riderequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passenger_id', sa.Integer(), nullable=False),
    sa.Column('from_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('desired_at', sa.DateTime(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=True),
    sa.Column('category', sa.Enum('regular', 'hospital', 'parcel', 'cargo', 'urgent', name='ridecategory'), nullable=False),
    sa.Column('with_kids', sa.Boolean(), nullable=False),
    sa.Column('baggage', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('for_relative_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('voice_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_riderequest_from_city'), 'riderequest', ['from_city'], unique=False)
    op.create_index(op.f('ix_riderequest_passenger_id'), 'riderequest', ['passenger_id'], unique=False)
    op.create_index(op.f('ix_riderequest_to_city'), 'riderequest', ['to_city'], unique=False)
    op.create_table('sosevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sosevent_user_id'), 'sosevent', ['user_id'], unique=False)
    op.create_table('tgauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tgauth_request_id'), 'tgauth', ['request_id'], unique=True)
    op.create_table('tripshare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('last_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tripshare_booking_id'), 'tripshare', ['booking_id'], unique=False)
    op.create_table('trustedcontact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notify_by_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trustedcontact_user_id'), 'trustedcontact', ['user_id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('passenger', 'driver', 'admin', name='userrole'), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('telegram_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('vk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('whatsapp_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=True)
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_user_vk_id'), 'user', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vk_id'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trustedcontact_user_id'), table_name='trustedcontact')
    op.drop_table('trustedcontact')
    op.drop_index(op.f('ix_tripshare_booking_id'), table_name='tripshare')
    op.drop_table('tripshare')
    op.drop_index(op.f('ix_tgauth_request_id'), table_name='tgauth')
    op.drop_table('tgauth')
    op.drop_index(op.f('ix_sosevent_user_id'), table_name='sosevent')
    op.drop_table('sosevent')
    op.drop_index(op.f('ix_riderequest_to_city'), table_name='riderequest')
    op.drop_index(op.f('ix_riderequest_passenger_id'), table_name='riderequest')
    op.drop_index(op.f('ix_riderequest_from_city'), table_name='riderequest')
    op.drop_table('riderequest')
    op.drop_index(op.f('ix_ride_to_city'), table_name='ride')
    op.drop_index(op.f('ix_ride_from_city'), table_name='ride')
    op.drop_index(op.f('ix_ride_driver_id'), table_name='ride')
    op.drop_table('ride')
    op.drop_index(op.f('ix_report_reporter_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_rating_rater_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_ratee_id'), table_name='rating')
    op.drop_index(op.f('ix_rating_booking_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_index(op.f('ix_otpcode_phone'), table_name='otpcode')
    op.drop_table('otpcode')
    op.drop_index(op.f('ix_message_booking_id'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_driverprofile_user_id'), table_name='driverprofile')
    op.drop_table('driverprofile')
    op.drop_index(op.f('ix_devicetoken_user_id'), table_name='devicetoken')
    op.drop_index(op.f('ix_devicetoken_token'), table_name='devicetoken')
    op.drop_table('devicetoken')
    op.drop_index(op.f('ix_booking_ride_id'), table_name='booking')
    op.drop_index(op.f('ix_booking_passenger_id'), table_name='booking')
    op.drop_table('booking')
    op.drop_index(op.f('ix_block_user_id'), table_name='block')
    op.drop_table('block')
    op.drop_index(op.f('ix_adevent_event_type'), table_name='adevent')
    op.drop_index(op.f('ix_adevent_ad_id'), table_name='adevent')
    op.drop_table('adevent')
    # ### end Alembic commands ###
