"""add foreign keys

Revision ID: c5bb69cf495d
Revises: 75accea6f8bd
Create Date: 2026-06-27 15:53:29.833447

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bb69cf495d'
down_revision: Union[str, Sequence[str], None] = '75accea6f8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'block', 'user', ['blocked_user_id'], ['id'])
    op.create_foreign_key(None, 'block', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'booking', 'user', ['passenger_id'], ['id'])
    op.create_foreign_key(None, 'booking', 'ride', ['ride_id'], ['id'])
    op.create_foreign_key(None, 'devicetoken', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'driverprofile', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'message', 'booking', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'message', 'user', ['sender_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'user', ['rater_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'booking', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'user', ['ratee_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['reporter_id'], ['id'])
    op.create_foreign_key(None, 'report', 'user', ['target_user_id'], ['id'])
    op.alter_column('ride', 'pickup',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ride', 'recurrence',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'none'::character varying"))
    op.create_foreign_key(None, 'ride', 'user', ['driver_id'], ['id'])
    op.add_column('riderequest', sa.Column('voice_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('riderequest', sa.Column('transcript', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'riderequest', 'user', ['passenger_id'], ['id'])
    op.create_foreign_key(None, 'sosevent', 'booking', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'sosevent', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'tripshare', 'trustedcontact', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'tripshare', 'booking', ['booking_id'], ['id'])
    op.create_foreign_key(None, 'trustedcontact', 'user', ['user_id'], ['id'])
    op.drop_index(op.f('idx_user_telegram_id'), table_name='user')
    op.drop_index(op.f('idx_user_vk_id'), table_name='user')
    op.drop_index(op.f('idx_user_whatsapp_verified'), table_name='user')
    op.create_index(op.f('ix_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_user_vk_id'), 'user', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_vk_id'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_id'), table_name='user')
    op.create_index(op.f('idx_user_whatsapp_verified'), 'user', ['whatsapp_verified'], unique=False)
    op.create_index(op.f('idx_user_vk_id'), 'user', ['vk_id'], unique=True)
    op.create_index(op.f('idx_user_telegram_id'), 'user', ['telegram_id'], unique=True)
    op.drop_constraint(None, 'trustedcontact', type_='foreignkey')
    op.drop_constraint(None, 'tripshare', type_='foreignkey')
    op.drop_constraint(None, 'tripshare', type_='foreignkey')
    op.drop_constraint(None, 'sosevent', type_='foreignkey')
    op.drop_constraint(None, 'sosevent', type_='foreignkey')
    op.drop_constraint(None, 'riderequest', type_='foreignkey')
    op.drop_column('riderequest', 'transcript')
    op.drop_column('riderequest', 'voice_url')
    op.drop_constraint(None, 'ride', type_='foreignkey')
    op.alter_column('ride', 'recurrence',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('ride', 'pickup',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'report', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'driverprofile', type_='foreignkey')
    op.drop_constraint(None, 'devicetoken', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'block', type_='foreignkey')
    op.drop_constraint(None, 'block', type_='foreignkey')
    # ### end Alembic commands ###
